mod agent;
mod app;
mod config_edit;
mod config_reload;
mod config_render;
mod controls;
mod copy;
mod data_path;
mod fields;
mod generated_resources;
mod hit;
mod local_profile;
mod observation_setup;
mod process_catalog_task;
mod process_view;
mod processes;
mod render;
mod runtime_actions;
mod runtime_attachment;
mod runtime_reconcile;
mod runtime_status;
mod terminal;
mod text;
mod traffic;
mod wire;

pub(crate) use config_edit::TuiError;
pub(crate) use terminal::{TuiOptions, run_tui};
