mod error;
mod model;
mod tls;
mod validation;

pub use error::{ConfigError, ConfigValidationError, ConfigViolation};
pub use model::{
    AdminConfig, AdminPrometheusConfig, AgentConfig, CaptureBackend, CaptureConfig,
    CaptureEventFeedCaptureConfig, CaptureSelection, CompressionCodecName,
    ConnectionEnforcementBackendConfig, DEFAULT_ADMIN_PROMETHEUS_LISTEN_ADDR,
    DEFAULT_ENFORCEMENT_POLICY_RELOAD_REMOTE_POLL_INTERVAL_MS,
    DEFAULT_ENFORCEMENT_POLICY_RELOAD_WATCH_DEBOUNCE_MS, DEFAULT_EXPORT_BATCHES_PER_SINK_PER_TICK,
    DEFAULT_EXPORT_FAILURE_BACKOFF_INITIAL_MS, DEFAULT_EXPORT_FAILURE_BACKOFF_MAX_MS,
    DEFAULT_EXPORT_FAILURE_BACKOFF_MULTIPLIER, DEFAULT_EXPORT_RETENTION_PRUNE_BATCH_LIMIT,
    DEFAULT_EXPORT_RETENTION_SWEEP_INTERVAL_MS, DEFAULT_EXPORT_SINK_TIMEOUT_MS,
    DEFAULT_EXPORT_WORKER_INTERVAL_MS, DEFAULT_INGRESS_RETENTION_PRUNE_BATCH_LIMIT,
    DEFAULT_INGRESS_RETENTION_SWEEP_INTERVAL_MS, DEFAULT_POLICY_RELOAD_REMOTE_POLL_INTERVAL_MS,
    DEFAULT_POLICY_RELOAD_WATCH_DEBOUNCE_MS, DEFAULT_POLICY_RUNTIME_ERROR_DISABLE_THRESHOLD,
    DEFAULT_PROBE_HOME_STATE_DIR, DEFAULT_REMOTE_ENFORCEMENT_POLICY_BODY_LIMIT_BYTES,
    DEFAULT_REMOTE_POLICY_BUNDLE_BODY_LIMIT_BYTES, DEFAULT_TLS_DECRYPT_HINT_REFRESH_INTERVAL_MS,
    DEFAULT_TLS_PLAINTEXT_RECONCILE_INTERVAL_MS,
    DEFAULT_TRANSPARENT_MITM_BACKEND_READINESS_FAILURE_THRESHOLD,
    DEFAULT_TRANSPARENT_MITM_BACKEND_READINESS_INTERVAL_MS,
    DEFAULT_TRANSPARENT_MITM_BACKEND_READINESS_TIMEOUT_MS,
    DEFAULT_TRANSPARENT_MITM_POLICY_HOOK_MAX_RESPONSE_BYTES,
    DEFAULT_TRANSPARENT_MITM_POLICY_HOOK_TIMEOUT_MS,
    DEFAULT_TRANSPARENT_PROXY_HEALTH_PROBE_FAILURE_THRESHOLD,
    DEFAULT_TRANSPARENT_PROXY_HEALTH_PROBE_INTERVAL_MS,
    DEFAULT_TRANSPARENT_PROXY_HEALTH_PROBE_TIMEOUT_MS, EbpfCaptureConfig, EnforcementConfig,
    EnforcementInterceptionConfig, EnforcementPolicyConfig, EnforcementPolicyManifest,
    EnforcementPolicyReloadConfig, EnforcementPolicySourceConfig, ExportFailureBackoffConfig,
    ExportQueueRetentionConfig, ExportRuntimeConfig, ExportWorkerRuntimeConfig,
    ExportWorkerScheduleConfig, ExporterConfig, ExporterTlsConfig, ExporterTransportConfig,
    ExporterWorkerConfig, FALLBACK_PROBE_HOME, FilesystemTlsMaterialStoreConfig,
    IngressJournalRetentionConfig, LibpcapCaptureConfig, LiveCaptureBackend,
    MAX_ENFORCEMENT_POLICY_RELOAD_REMOTE_POLL_INTERVAL_MS,
    MAX_ENFORCEMENT_POLICY_RELOAD_WATCH_DEBOUNCE_MS, MAX_POLICY_RELOAD_REMOTE_POLL_INTERVAL_MS,
    MAX_POLICY_RELOAD_WATCH_DEBOUNCE_MS, MAX_REMOTE_ENFORCEMENT_POLICY_BODY_LIMIT_BYTES,
    MAX_REMOTE_POLICY_BUNDLE_BODY_LIMIT_BYTES, MAX_TLS_DECRYPT_HINT_REFRESH_INTERVAL_MS,
    MAX_TLS_PLAINTEXT_RECONCILE_INTERVAL_MS,
    MAX_TRANSPARENT_MITM_BACKEND_READINESS_FAILURE_THRESHOLD,
    MAX_TRANSPARENT_MITM_BACKEND_READINESS_INTERVAL_MS,
    MAX_TRANSPARENT_MITM_BACKEND_READINESS_TIMEOUT_MS,
    MAX_TRANSPARENT_MITM_POLICY_HOOK_MAX_RESPONSE_BYTES,
    MAX_TRANSPARENT_MITM_POLICY_HOOK_TIMEOUT_MS,
    MAX_TRANSPARENT_PROXY_HEALTH_PROBE_FAILURE_THRESHOLD,
    MAX_TRANSPARENT_PROXY_HEALTH_PROBE_INTERVAL_MS, MAX_TRANSPARENT_PROXY_HEALTH_PROBE_TIMEOUT_MS,
    MIN_ENFORCEMENT_POLICY_RELOAD_REMOTE_POLL_INTERVAL_MS,
    MIN_ENFORCEMENT_POLICY_RELOAD_WATCH_DEBOUNCE_MS, MIN_POLICY_RELOAD_REMOTE_POLL_INTERVAL_MS,
    MIN_POLICY_RELOAD_WATCH_DEBOUNCE_MS, MIN_TRANSPARENT_MITM_BACKEND_READINESS_FAILURE_THRESHOLD,
    MIN_TRANSPARENT_MITM_BACKEND_READINESS_INTERVAL_MS,
    MIN_TRANSPARENT_MITM_BACKEND_READINESS_TIMEOUT_MS,
    MIN_TRANSPARENT_MITM_POLICY_HOOK_MAX_RESPONSE_BYTES,
    MIN_TRANSPARENT_MITM_POLICY_HOOK_TIMEOUT_MS,
    MIN_TRANSPARENT_PROXY_HEALTH_PROBE_FAILURE_THRESHOLD,
    MIN_TRANSPARENT_PROXY_HEALTH_PROBE_INTERVAL_MS, MIN_TRANSPARENT_PROXY_HEALTH_PROBE_TIMEOUT_MS,
    ObservationDataPathMode, PROBE_HOME_ENV, PlaintextFeedCaptureConfig, PlaintextTlsConfig,
    PolicyConfig, PolicyReloadConfig, PolicySourceConfig, ProcessObservationConfig,
    RemoteEnforcementPolicyBodyLimitBytes, RemoteEnforcementPolicyBodyLimitError,
    RemotePolicyBundleBodyLimitBytes, RemotePolicyBundleBodyLimitError, StorageConfig,
    StorageRetentionConfig, TlsConfig, TlsMaterialConfig, TlsMaterialKind, TlsMaterialStoreConfig,
    TlsPlaintextDecryptHintConfig, TlsPlaintextInstrumentationConfig,
    TransparentInterceptionDirectionConfig, TransparentInterceptionDisabledProxyIntent,
    TransparentInterceptionEnabledProxyIntent, TransparentInterceptionIntentViolation,
    TransparentInterceptionL7ModeConfig, TransparentInterceptionMitmBackendConfig,
    TransparentInterceptionMitmBackendIntent,
    TransparentInterceptionMitmBackendReadinessProbeConfig,
    TransparentInterceptionMitmBackendReadinessProbeIntent,
    TransparentInterceptionMitmClientTrustConfig, TransparentInterceptionMitmClientTrustIntent,
    TransparentInterceptionMitmClientTrustModeConfig, TransparentInterceptionMitmConfig,
    TransparentInterceptionMitmIntentViolation, TransparentInterceptionMitmManagedProcessConfig,
    TransparentInterceptionMitmManagedProcessIntent,
    TransparentInterceptionMitmPlaintextBridgeConfig,
    TransparentInterceptionMitmPlaintextBridgeIntent,
    TransparentInterceptionMitmPlaintextBridgeModeConfig,
    TransparentInterceptionMitmPolicyHookConfig,
    TransparentInterceptionMitmPolicyHookEndpointIntent,
    TransparentInterceptionMitmPolicyHookIntent, TransparentInterceptionMitmPolicyHookModeConfig,
    TransparentInterceptionMitmProductProxyConfig, TransparentInterceptionMitmProductProxyIntent,
    TransparentInterceptionMitmProductProxyLauncherConfig,
    TransparentInterceptionMitmProductProxyLauncherIntent,
    TransparentInterceptionMitmProductProxyUpstreamDiscoveryConfig,
    TransparentInterceptionMitmProductProxyUpstreamDiscoveryIntent,
    TransparentInterceptionMitmProductProxyUpstreamDiscoveryModeConfig,
    TransparentInterceptionMitmProductProxyUpstreamRouteConfig,
    TransparentInterceptionMitmProductProxyUpstreamRouteIntent,
    TransparentInterceptionMitmProductProxyUpstreamTlsModeConfig,
    TransparentInterceptionMitmProductProxyUpstreamTlsModeIntent,
    TransparentInterceptionOutboundProxyIntent, TransparentInterceptionOutboundProxyModeIntent,
    TransparentInterceptionOutboundProxySelfBypassIntent, TransparentInterceptionProxyConfig,
    TransparentInterceptionProxyHealthProbeConfig, TransparentInterceptionProxyHealthProbeIntent,
    TransparentInterceptionProxyIntent, TransparentInterceptionProxyIntentViolation,
    TransparentInterceptionProxyModeConfig, TransparentInterceptionProxySelfBypassConfig,
    TransparentInterceptionStrategyConfig, TransparentInterceptionStrategyDescriptor,
    default_admin_socket_path, default_config_path, default_enforcement_policy_path,
    default_export_file_path, default_export_unix_http_socket_path,
    default_mitm_ca_certificate_path, default_mitm_ca_private_key_path,
    default_mitm_plaintext_bridge_path, default_mitm_tls_root, default_storage_path,
    has_enabled_remote_policy_bundle_source, probe_home, probe_home_path,
};
